//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prospect.ProspectTestData._TemplateFolder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TAccounts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TAccounts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Prospect.ProspectTestData._TemplateFolder.TAccounts", typeof(TAccounts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houston7890.
        /// </summary>
        public static string password_BPA2TestUser1 {
            get {
                return ResourceManager.GetString("password_BPA2TestUser1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houston7890.
        /// </summary>
        public static string password_BPA2TestUser10 {
            get {
                return ResourceManager.GetString("password_BPA2TestUser10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houston7890.
        /// </summary>
        public static string password_BPA2TestUser2 {
            get {
                return ResourceManager.GetString("password_BPA2TestUser2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houston7890.
        /// </summary>
        public static string password_BPA2TestUser3 {
            get {
                return ResourceManager.GetString("password_BPA2TestUser3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houston7890.
        /// </summary>
        public static string password_BPA2TestUser4 {
            get {
                return ResourceManager.GetString("password_BPA2TestUser4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houston7890.
        /// </summary>
        public static string password_BPA2TestUser5 {
            get {
                return ResourceManager.GetString("password_BPA2TestUser5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houston7890.
        /// </summary>
        public static string password_BPA2TestUser6 {
            get {
                return ResourceManager.GetString("password_BPA2TestUser6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houston7890.
        /// </summary>
        public static string password_BPA2TestUser7 {
            get {
                return ResourceManager.GetString("password_BPA2TestUser7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houston7890.
        /// </summary>
        public static string password_BPA2TestUser8 {
            get {
                return ResourceManager.GetString("password_BPA2TestUser8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houston7890.
        /// </summary>
        public static string password_BPA2TestUser9 {
            get {
                return ResourceManager.GetString("password_BPA2TestUser9", resourceCulture);
            }
        }
    }
}
